### ISSUE TITLE
Epic: Enhance the `concat_elements` kernel

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-rs#1772]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
`concat_elements` is a new compute kernel and there are lots of things to do. So we create an epic
issue to track them.

# Safety
No bug is found so far.

# Performance
- [ ] Add benchmark

# New features
- [x] https://github.com/apache/arrow-rs/issues/1755
- [x] https://github.com/apache/arrow-rs/issues/1748
- [ ] Add support for binary array
- [ ] Add support for fixed size binary array
- [ ] Add support for list array
- [ ] Add support for fixed size list array
- [ ] Add support for map array

**Comment by Jefffrey** [comment]
we support all string + binary types in `concat_elements_dyn` now; given this is a function under `arrow-string` i dont think we need to aim for including map/list type support so i'll close this now
