### ISSUE TITLE
[EPIC] Support bitwise op in arrow-rs

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-rs#2702]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

from the issue about bitwise op in the datafusion, we should migration the bitwise op to the arrow-rs

- [x] bitwise AND https://github.com/apache/arrow-rs/pull/2703
- [x] bitwise OR https://github.com/apache/arrow-rs/pull/2716
- [x] bitwise XOR https://github.com/apache/arrow-rs/pull/2716
- [x] bitwise NOT https://github.com/apache/arrow-rs/pull/2716
- [ ] left/right shift: https://github.com/apache/arrow-rs/issues/2741
- [x] benchmark for bitwise op https://github.com/apache/arrow-rs/pull/2718

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
I think moving these kernels to arrow is a great idea -- thank you @liukun4515  -- and likely the experts in arrow-rs will be able to offer some suggestions on how to improve the performance

**Comment by liukun4515** [comment]
@alamb @tustvold 

When I implement the left/right shift operation for the bitwise, I meet a issue.

In the rust, the operation` << or shl` will be overflow which don't like the ` bitand, bitor`.
The `warpping_shl` just support `wrapping_shl(self, u32) -> Self`, the `wrapping_shl` for generic type is feature in the rust  https://github.com/rust-lang/rust/issues/90080
Do you have any thoughts about that?


Can we add a new trait like `ArrowNativeTypeOp` to support the `shl_wrapping(self, u32) -> Self`?

**Comment by tustvold** [comment]
The issue you've linked relates to const versions of the functions, looking at the docs wrapping_shl seems to be defined for all the primitive types - e.g. https://doc.rust-lang.org/stable/std/primitive.i64.html#method.wrapping_shl

**Comment by liukun4515** [comment]
> The issue you've linked relates to const versions of the functions, looking at the docs wrapping_shl seems to be defined for all the primitive types - e.g. https://doc.rust-lang.org/stable/std/primitive.i64.html#method.wrapping_shl

But the `rhs` type only be `u32` for any primitive typs.

My point is the api of https://doc.rust-lang.org/stable/src/core/num/wrapping.rs.html#87.

Do you means that we can implement all data type with converting the `rhs` value to the type of `u32`?

**Comment by tustvold** [comment]
Tbh I'm not sure I fully understand the use-case for left or right shifting based on anything but a scalar, what does C++ do?

**Comment by alamb** [comment]
> Tbh I'm not sure I fully understand the use-case for left or right shifting based on anything but a scalar, what does C++ do?

I think the biggest argument in my mind is for completeness -- I can cook up some examples when one might use it but they would definitely be contrived.

**Comment by alamb** [comment]
I don't have any thoughts or opinions on the shift implementation -- I defer to @tustvold
