### ISSUE TITLE
Implement FlightSQL [EPIC]

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#3301]
As discussed in https://github.com/apache/arrow-rs/issues/1323, there is now sufficient community interest in moving forward with a Rust FlightSQL implementation. Thanks to @avantgardnerio and @wangfenjin  we have basic POC level client and server implementations behind the `--features=flight-sql-experimental` feature flag. 

This ticket tracks the work needed to change the feature flag from `flight-sql-experimental` to `flight-sql` (aka that we are comfortable saying that the rust client supports FlightSQL)

# Known work items

## Basics

- [x] https://github.com/apache/arrow-rs/pull/1386
- [x] https://github.com/apache/arrow-rs/issues/1413
- [x] https://github.com/apache/arrow-rs/issues/3312
- [x] #3371
- [ ] Update documentation / examples to use higher level encode/decode streams and clients

## Testing
- [ ] #3400
- [ ] https://github.com/apache/arrow-rs/issues/2409

## FlightSQL Client
- [ ] #3308
- [x] #3309
- [x] https://github.com/apache/arrow-rs/issues/3310

## Performance
- [ ] https://github.com/apache/arrow-rs/issues/3389

**Comment by Dandandan** [comment]
One improvement for flightsql (and flight as well) is to support sending/tracking dictionaries in the API (to avoid sending shared dictionaries for every recordbatch.

**Comment by alamb** [comment]
> One improvement for flightsql (and flight as well) is to support sending/tracking dictionaries in the API (to avoid sending shared dictionaries for every recordbatch.

Thanks @Dandandan  -- I have filed https://github.com/apache/arrow-rs/issues/3312

**Comment by alamb** [comment]
An update here on my end: I have been working on FlightSQL as part of IOx and have several ideas on how to consolidate implementations and what would be useful to contirbute back upstream

My high level proposal is 

1. Create a general Flight client wrapper on top of the automatically generated one that handle streaming RecordBatch conversions, for those who want it -- I have seen versions of this code in Ballista, now the arrow flighsql client (derived from Ballista) and IOx so I think it is a good common building block
2. Build a FlightSQL client on top of the general FlightClient that handles marshalling / unmarshalling the protobuf messages appropriate. 

I plan a more full featured proposal in the next day or two

**Comment by tustvold** [comment]
Is this still tracking anything meaningful?

**Comment by alamb** [comment]
I don't think so 🤔  Maybe we should simply consider renaming the feature flag to `flightsql` rather than `flightsql-experimental` 🤔
