### ISSUE TITLE
[EPIC] Implement  `StringViewArray` and `BinaryViewArray`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#5374]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Recently two new types were added to the Arrow format that make it more suitable for certain types of operations on strings

Specifically when doing filtering / take with string data, creating a new `Utf8Array` requires copying the strings to a new, packed binary buffer. The "VariableSizeBinaryView" was designed to solve this limitation and recently added to the Arrow spec.

**Describe the solution you'd like**
I would like to implement `StringViewArray` and `BinaryViewArray` following the spec:
The spec:  https://arrow.apache.org/docs/format/Columnar.html#variable-size-binary-view-layout
https://github.com/apache/arrow/blob/3fe598ae4dfd7805ab05452dd5ed4b0d6c97d8d5/format/Schema.fbs#L187-L205

Initially, I would suggest we get the basic types in place:
- [x] #5468
- [x] #5469
- [x] Add `BinaryViewArray` implementation and layout and basic construction

Then as follow on PRs, add support for key features
- [x] https://github.com/apache/arrow-rs/issues/5506
- [x] https://github.com/apache/arrow-rs/issues/5507
- [x] https://github.com/apache/arrow-rs/issues/5508
- [x] https://github.com/apache/arrow-rs/issues/5509
- [x] https://github.com/apache/arrow-rs/issues/5510
- [x] https://github.com/apache/arrow-rs/issues/5511
- [x] https://github.com/apache/arrow-rs/issues/5861
- [x] https://github.com/apache/arrow-rs/issues/5897
- [x] https://github.com/apache/arrow-rs/issues/5921
- [x] https://github.com/apache/arrow-rs/pull/5936
- [x] https://github.com/apache/arrow-rs/pull/5963#pullrequestreview-2142465855
- [x] https://github.com/apache/arrow-rs/pull/5931
- [x] #5903
- [x] https://github.com/apache/arrow-rs/issues/5513
- [x] #5530
- [ ] Add arrow IPC cross implementation serialization tests
- [x] #5904
- [x] https://github.com/apache/arrow-rs/issues/5910
- [x] https://github.com/apache/arrow-rs/issues/5893
- [x] https://github.com/apache/arrow-rs/issues/6052
- [x] https://github.com/apache/arrow-rs/issues/6094
- [x] https://github.com/apache/arrow-rs/issues/6088
- [ ] `interleave` (used in Sort)

Potential Follow ons / additional optimizations
- [x] https://github.com/apache/arrow-rs/issues/5945
- [x] https://github.com/apache/arrow-rs/issues/6034
- [ ] https://github.com/apache/arrow-rs/issues/6057
- [ ] https://github.com/apache/arrow-rs/issues/6058
- [ ] https://github.com/apache/arrow-rs/issues/5951

**Describe alternatives you've considered**
I think a good plan would be to dust off the prototype on https://github.com/apache/arrow-rs/pull/4585 from @tustvold  (linked from https://github.com/apache/arrow-rs/issues/4253). 

Initially, the idea would be to dust off the PR and split it into a few smaller PRs with tests and docs. 

**Additional context**
Polars implemented it recently in rust so that can serve as a motivation
Blog Post https://pola.rs/posts/polars-string-type/
https://twitter.com/RitchieVink/status/1749466861069115790 

Facebook/Velox's take: https://engineering.fb.com/2024/02/20/developer-tools/velox-apache-arrow-15-composable-data-management/

Related PRs:
https://github.com/pola-rs/polars/pull/13748 
https://github.com/pola-rs/polars/pull/13839
https://github.com/pola-rs/polars/pull/13489

**Comment by alamb** [comment]
@tustvold  pointed out the previous PR he made was https://github.com/apache/arrow-rs/pull/4585

We can probably dust that off and get it ready to merge as part of this project

**Comment by alamb** [comment]
@kallisti-dev I believe may do some work on this.

I suggested breaking it down into a sequence of PRs (keeping notes of what is not yet implemented along the way)

Specifically, I suggest the first PR should have:
1. The new `DataType`
2. The new `StringViewArray` and `impl Array`
3. A basic constructor for creating and validating StringViewArray 
4. Any feature (e.g. IPC support, parquet support, etc) should return a `Arrow::NotYetImplemented` error (rather than `panic`)

That will likely be a sizeable PR on its own.

**Comment by alamb** [comment]
Post from Velox on iimportance of stringview: https://engineering.fb.com/2024/02/20/developer-tools/velox-apache-arrow-15-composable-data-management/

**Comment by alamb** [comment]
Moving an update from  @sundy-li  and @ariesdevil  from https://github.com/apache/arrow-rs/pull/4585#issuecomment-1965896483  to here for visibility

I believe @ariesdevil is considering working on this relatively shortly

> Hi @alamb, I'm willing to work on this feature after [datafuselabs/databend#14662](https://github.com/datafuselabs/databend/pull/14662) is finished.


@XiangpengHao, who will be working with us at InfluxData this summer (starting in May) is also interested in this project, so when we get closer to May we'll engage more fully and perhaps we can figure out how to split up some of the work.

**Comment by ariesdevil** [comment]
> Moving an update from @sundy-li and @ariesdevil from [#4585 (comment)](https://github.com/apache/arrow-rs/pull/4585#issuecomment-1965896483) to here for visibility↳
> 
> I believe @ariesdevil is considering working on this relatively shortly↳
> 
> > Hi @alamb, I'm willing to work on this feature after [datafuselabs/databend#14662](https://github.com/datafuselabs/databend/pull/14662) is finished.↳
> 
> @XiangpengHao, who will be working with us at InfluxData this summer (starting in May) is also interested in this project, so when we get closer to May we'll engage more fully and perhaps we can figure out how to split up some of the work.

Do we have a group similar to Discord or Slack?

**Comment by alamb** [comment]
> Do we have a group similar to Discord or Slack?

@ariesdevil  There is both discord and slack -- links are here https://github.com/apache/arrow-rs?tab=readme-ov-file#arrow-rust-community

The discord server doesn't require an invite and seems to be a bit more active recently

**Comment by Kikkon** [comment]
Hi @alamb 

I'm interested in the progress of this issue regarding the addition of ListViewArray and LargeListViewArray to arrow-rs. I've been following the discussion and would like to know if there have been any updates or if there's anything specific I can assist with to help move this forward.

**Comment by alamb** [comment]
@ariesdevil  says they have time to begin work on this so I will begin filing subtasks

**Comment by alamb** [comment]
Update here is that @ariesdevil  has a PR https://github.com/apache/arrow-rs/pull/5481 that we plan to merge tomorrow

**Comment by cgbur** [comment]
Is there an issue to make sure that parquet support for the new arrow view types are supported. [Currently can not use with the parquet writer when they are specified in the schema](https://github.com/apache/arrow-rs/blob/f41c2a4e5a33e482e12351051d77d0e059f28e33/parquet/src/arrow/schema/mod.rs#L468). 

I am actually more familiar with Arrow than I am Parquet so excuse the question: is there an official Parquet spec or implementation plan for the view types?

**Comment by ariesdevil** [comment]
I'm working on read/write parquet for view types.

**Comment by alamb** [comment]
> I'm working on read/write parquet for view types.

I filed https://github.com/apache/arrow-rs/issues/5530 to track

**Comment by alamb** [comment]
BTW if anyone is interested, I have a proposal for how to improve manipulating the views in Rust https://github.com/apache/arrow-rs/pull/5619 (I really enjoy the rust type system in general -- it is quite cool)

**Comment by alamb** [comment]
Update here: thanks to @ariesdevil  and @XiangpengHao  and @RinChanNOWWW  we have pretty good basic support for StringView in arrow-rs -- we have basic construction, cast and soon comparison functionality complete. Also, we can now read directly from parquet into StringView arrays https://github.com/apache/arrow-rs/issues/5530

We have also begun the work to integrate this into DataFusion, which is tracked in https://github.com/apache/datafusion/issues/10918

**Comment by alamb** [comment]
Update here is that most of the basic StringView work for basic scanning / filtering is done. There will likely be an large tail of places to implement special StringView support as follw on.

Over the next week or two I plan to file a new ticket for the remaining known work and close this ticket down

**Comment by alamb** [comment]
Given we have now released all the basic support in arrow 52.0.0 am going to claim we are done with the initial implementation and close this ticket 🎉 

Huge kudos to everyone who helped including @RinChanNOWWW @ariesdevil @tustvold @XiangpengHao and @a10y  (sorry if I forgot anyone) 

I am collecting additional potential work items in https://github.com/apache/arrow-rs/issues/6163
