### ISSUE TITLE
[Epic] A collection of `StringView` / `BinaryView` improvements

### ISSUE THREAD

**Issue by alamb** [apache/arrow-rs#6163]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
arrow-rs / parquet now supports `StringView` 🎉  -- see https://github.com/apache/arrow-rs/issues/5374 for the initial work

This epic collects a variety of tasks related to improving  support for this type. Please leave a comment if you have other tickets we should add

Functionality
- [x] https://github.com/apache/arrow-rs/issues/6162
- [x] https://github.com/apache/arrow-rs/issues/6164
- [x] https://github.com/apache/arrow-rs/issues/6170

Performance Improvements:
- [x] https://github.com/apache/arrow-rs/issues/6058
- [x] https://github.com/apache/arrow-rs/issues/5951
- [x] https://github.com/apache/arrow-rs/issues/6167
- [x] https://github.com/apache/arrow-rs/pull/6142
- [x] https://github.com/apache/arrow-rs/issues/6057
- [x] https://github.com/apache/arrow-rs/issues/6370

**Describe the solution you'd like**

**Comment by a10y** [comment]
Have another one that I'd love a review on 😄

It appears that while support for IPC format was added for view arrays, some things were missing from C Data Interface, PR here: https://github.com/apache/arrow-rs/pull/6368 

and corresponding ticket at https://github.com/apache/arrow-rs/issues/6366

**Comment by Rich-T-kid** [comment]
@Jefffrey I think this can be closed

**Comment by Jefffrey** [comment]
any further improvements can just come as individual issues, no need to link to the epic
